import {
  RekognitionClient,
  DetectFacesCommand,
  DetectLabelsCommand,
  type FaceDetail,
} from '@aws-sdk/client-rekognition';
import {
  BedrockRuntimeClient,
  ConverseCommand,
} from '@aws-sdk/client-bedrock-runtime';

// Single source of truth for the verdict shape; the browser re-declares a
// matching type in src/feature/rekognition.ts (no cross-boundary import).
export type FaceFlag = { value: boolean; confidence: number };
export type Label = { name: string; confidence: number };
export type Roast = { score: number; type: string; redFlags: string[]; findings: string[] };
export type RekognitionVerdict = {
  faceFound: boolean;
  sunglasses?: FaceFlag;
  eyeglasses?: FaceFlag;
  smile?: FaceFlag;
  eyesOpen?: FaceFlag;
  mouthOpen?: FaceFlag;
  beard?: FaceFlag;
  emotion?: { type: string; confidence: number };
  pose?: { yaw: number; pitch: number; roll: number };
  /** Objects/scene labels (outfit, furniture, room, clutter, …). */
  labels?: Label[];
  /** Roast + toxicity %, generated by Bedrock Nova Lite 2 from the data above. */
  roast?: Roast;
};

const NOVA_MODEL = process.env.BEDROCK_MODEL_ID || 'us.amazon.nova-2-lite-v1:0';

const REGION =
  process.env.REKOGNITION_REGION || process.env.AWS_REGION || 'us-east-1';

// Reused across warm invocations; credentials come from the default chain
// (env vars / shared config / instance role) — never from the browser.
let client: RekognitionClient | null = null;
function getClient(): RekognitionClient {
  if (!client) client = new RekognitionClient({ region: REGION });
  return client;
}

function stripDataUrl(input: string): string {
  const comma = input.indexOf(',');
  return input.startsWith('data:') && comma !== -1 ? input.slice(comma + 1) : input;
}

function flag(value?: boolean, confidence?: number): FaceFlag | undefined {
  if (value === undefined) return undefined;
  return { value, confidence: Math.round(confidence ?? 0) };
}

function boxArea(face: FaceDetail): number {
  const b = face.BoundingBox;
  return b ? (b.Width ?? 0) * (b.Height ?? 0) : 0;
}

let bedrock: BedrockRuntimeClient | null = null;
function getBedrock(): BedrockRuntimeClient {
  if (!bedrock) bedrock = new BedrockRuntimeClient({ region: REGION });
  return bedrock;
}

const ROAST_SYSTEM = `Eres el jurado ácido de "ToxiCheck", una app de citas satírica española.
Recibes SOLO datos objetivos detectados por AWS Rekognition en una foto (cara, gafas, emoción, pose, objetos/ropa).
Devuelve un veredicto de toxicidad para ligar, con humor negro y mala leche (sin odio real ni insultos a grupos protegidos).
Responde SOLO JSON válido:
{
  "score": number (0-100, qué tan "red flag" es la persona según lo detectado),
  "type": string (etiqueta corta en mayúsculas, ej. "RED FLAG AMBULANTE"),
  "redFlags": string[] (4-5 frases en español, cada una BASADA en un dato concreto detectado: menciónalo),
  "findings": string[] (2-4 observaciones factuales y secas de lo que se ve, con un emoji al inicio, sin chiste, ej. "🕶️ Sin gafas de sol", "😐 Ánimo tranquilo")
}
Si no hay cara ni objetos, score bajo y frases sobre lo vacío que está todo.`;

/** Turn the raw Rekognition data into a roast + toxicity % via Bedrock Nova Lite 2. */
async function generateRoast(v: RekognitionVerdict): Promise<Roast | undefined> {
  try {
    const res = await getBedrock().send(
      new ConverseCommand({
        modelId: NOVA_MODEL,
        system: [{ text: ROAST_SYSTEM }],
        messages: [
          {
            role: 'user',
            content: [
              {
                text: `Datos de Rekognition (JSON):\n${JSON.stringify({
                  faceFound: v.faceFound,
                  sunglasses: v.sunglasses,
                  eyeglasses: v.eyeglasses,
                  smile: v.smile,
                  beard: v.beard,
                  emotion: v.emotion,
                  pose: v.pose,
                  labels: (v.labels ?? []).map((l) => l.name),
                })}`,
              },
            ],
          },
        ],
        inferenceConfig: { maxTokens: 600, temperature: 0.8 },
      }),
    );
    const text = res.output?.message?.content?.[0]?.text ?? '';
    const json = text.slice(text.indexOf('{'), text.lastIndexOf('}') + 1);
    const parsed = JSON.parse(json) as Roast;
    return {
      score: Math.max(0, Math.min(100, Math.round(Number(parsed.score) || 0))),
      type: String(parsed.type || 'SIN DIAGNOSTICAR'),
      redFlags: (Array.isArray(parsed.redFlags) ? parsed.redFlags : [])
        .map((s) => String(s))
        .slice(0, 5),
      findings: (Array.isArray(parsed.findings) ? parsed.findings : [])
        .map((s) => String(s))
        .slice(0, 4),
    };
  } catch (err) {
    console.error('[roast] Bedrock error:', err);
    return undefined;
  }
}

/** Run Rekognition DetectFaces on a base64 (or data-URL) JPEG/PNG frame. */
export async function analyzeFrame(image: string): Promise<RekognitionVerdict> {
  if (!image || typeof image !== 'string') {
    throw new Error('Missing image payload');
  }

  const bytes = Buffer.from(stripDataUrl(image), 'base64');
  const client = getClient();

  // Faces (expression/sunglasses) and labels (clothing/scene) run independently,
  // so a missing IAM permission on one still returns the other.
  const [facesRes, labelsRes] = await Promise.allSettled([
    client.send(
      new DetectFacesCommand({ Image: { Bytes: bytes }, Attributes: ['ALL'] }),
    ),
    client.send(
      new DetectLabelsCommand({ Image: { Bytes: bytes }, MaxLabels: 30, MinConfidence: 75 }),
    ),
  ]);

  if (facesRes.status === 'rejected' && labelsRes.status === 'rejected') {
    throw facesRes.reason; // both failed — surface the error to the client
  }

  const labels: Label[] =
    labelsRes.status === 'fulfilled'
      ? (labelsRes.value.Labels ?? [])
          .filter((l) => l.Name)
          .map((l) => ({ name: l.Name as string, confidence: Math.round(l.Confidence ?? 0) }))
      : [];

  const faces = facesRes.status === 'fulfilled' ? facesRes.value.FaceDetails ?? [] : [];
  if (faces.length === 0) {
    const noFace: RekognitionVerdict = { faceFound: false, labels };
    noFace.roast = await generateRoast(noFace);
    return noFace;
  }

  // Largest face = the subject of the selfie.
  const face = faces.reduce((a, b) => (boxArea(b) >= boxArea(a) ? b : a));

  const topEmotion = (face.Emotions ?? [])
    .slice()
    .sort((a, b) => (b.Confidence ?? 0) - (a.Confidence ?? 0))[0];

  const verdict: RekognitionVerdict = {
    faceFound: true,
    sunglasses: flag(face.Sunglasses?.Value, face.Sunglasses?.Confidence),
    eyeglasses: flag(face.Eyeglasses?.Value, face.Eyeglasses?.Confidence),
    smile: flag(face.Smile?.Value, face.Smile?.Confidence),
    eyesOpen: flag(face.EyesOpen?.Value, face.EyesOpen?.Confidence),
    mouthOpen: flag(face.MouthOpen?.Value, face.MouthOpen?.Confidence),
    beard: flag(face.Beard?.Value, face.Beard?.Confidence),
    emotion: topEmotion?.Type
      ? { type: topEmotion.Type, confidence: Math.round(topEmotion.Confidence ?? 0) }
      : undefined,
    pose: face.Pose
      ? {
          yaw: Math.round(face.Pose.Yaw ?? 0),
          pitch: Math.round(face.Pose.Pitch ?? 0),
          roll: Math.round(face.Pose.Roll ?? 0),
        }
      : undefined,
    labels,
  };
  verdict.roast = await generateRoast(verdict);
  return verdict;
}
